apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: author-testing-delay
spec:
  hosts:
    - authors
  http:
    - fault:
        delay:
          fixedDelay: 40s
          percent: 100
      route:
        - destination:
            host: authors
            port:
              number: 8080
    - route:
        - destination:
            host: authors
            port:
              number: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: author-testing-http-abort
spec:
  hosts:
    - authors
  http:
    - fault:
        abort:
          httpStatus: 500
          percent: 100
      route:
        - destination:
            host: authors
            port:
              number: 8080
    - route:
        - destination:
            host: authors
            port:
              number: 8080
